name: Node CI

on:
  push:
    branches: 
      - master
      - develop
      - feature/*
      - bugfix/*
      - hotfix/*
  pull_request:
    branches: 
      - master
      - develop
      - feature/*
      - bugfix/*
      - hotfix/*
jobs:
  build: 
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node_version: [8.x, 10.x, 12.x]
    runs-on: ${{ matrix.os }}
    steps:
      # Checkout Codebase
    - uses: actions/checkout@v1
      
      # Set Node Version
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
        
      # Get Cached Dependencies if Existing      
    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"
      
      # Caching of Dependencies
    - uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}:${{ matrix.node_version }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
          
      # Install Dependencies if not Cached
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn install --silent
          
      # Run Tests and Generate Coverate Report
    - name: Run tests
      run: yarn test:cov

      # Push Coverage to CodeCov
    - name: Codecov
      uses: codecov/codecov-action@v1.0.0
      if: matrix.os == 'ubuntu-latest' && matrix.node_version == '12.x'
      with:
        token: ${{secrets.CODECOV_TOKEN}} 
      
      # Send SMS to Notify of Status
    - name: 'Sending SMS Notification'
      uses: twilio-labs/actions-sms@v1
      if: matrix.os == 'ubuntu-latest' && matrix.node_version == '12.x'
      with:
        fromPhoneNumber: '+1(202) 740-9231'
        toPhoneNumber: '+1(781)5074468'
        message: 'A GitHub Action is becoming sentient'
      env:
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
        TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
        CI: true
